### DISCUSSION TITLE
Mounted onedrive as storage on linux and use that as a docker volume

### DISCUSSION THREAD

**Discussion by ghost** [jlesage/docker-jdownloader-2#196] [General]
Hi, I have my one drive mounted here /root/onedrive
i wanted to use this as host path and in container path /output

but whenever i download any file from jdownloader, it says output folder doesnt exist but it actually exist when i see inside container files and folders

this is my docker run command
docker run -d \
  --name=jdownloader-2 \
  -v /docker/appdata/jdownloader-2:/config:rw \
  -v /root/onedrive:/output:rw \
  -p 5800:5800 \
  -p 5900:5900 \
  -p 3129:3129 \
  jlesage/jdownloader-2

**Comment by mr-manuel** [comment]
The commands seem to be fine. Try to change the permissions for `/root/onedrive` to `777` with `chmod 755 /root/onedrive`. Then you see, if eventually the jdownloader creates a folder with a different user.

**Reply by ghost** [reply]
![image](https://github.com/jlesage/docker-jdownloader-2/assets/130595576/5ee20c23-2de3-4df7-ac05-b2b25a20dc09)
Hey i tried what u said , but it doesnt create the folder but when i go to container inside and check its there. why its happening like this

**Reply by mr-manuel** [reply]
What should I see in the screenshot?

**Reply by mr-manuel** [reply]
Did you really execute your command like this?

```bash
docker run -d
--name=jdownloader-2
-v /docker/appdata/jdownloader-2:/config:rw
-v /root/onedrive:/output:rw
-p 5800:5800
-p 5900:5900
-p 3129:3129
jlesage/jdownloader-2
```

If you don't execute it in one line, I'm not sure if the command is executed successfully. Did you escape the new line like this?

```bash
docker run -d \
--name=jdownloader-2 \
-v /docker/appdata/jdownloader-2:/config:rw \
-v /root/onedrive:/output:rw \
-p 5800:5800 \
-p 5900:5900 \
-p 3129:3129 \
jlesage/jdownloader-2
```

I would recommend you to use docker compose. Create a `docker-compose.yml` in an empty folder with this content:
```yml
name: jdownloader-2
services:
    jdownloader-2:
        container_name: jdownloader-2
        volumes:
            - /docker/appdata/jdownloader-2:/config:rw
            - /root/onedrive:/output:rw
        ports:
            - 5800:5800
            - 5900:5900
            - 3129:3129
        image: jlesage/jdownloader-2
```

then go to the folder where the `docker-compose.yml` is located and execute this commands:
```bash
# downloads the image
docker compose pull

# create and run the container
docker compose up -d
```

**Reply by ghost** [reply]
Hi, I used your docker compose yml file and still the folder isnt getting created, i have 777 permission
![image](https://github.com/jlesage/docker-jdownloader-2/assets/130595576/b7ab4851-1e81-4a31-8433-eab5fd3100cd)
but when i give different path in yaml file instead of output then output folder is getting created.
Idk why
Also im sure that my mounted volume of rclone its in this location: /root/onedrive

```
version: '3.3'
services:
  jdownloader-2:
    container_name: jdownloader-2
    volumes:
      - /docker/appdata/jdownloader-2:/config:rw
      - /root/onedrive:/output:rw
    ports:
      - 5800:5800
      - 5900:5900
      - 3129:3129
    image: jlesage/jdownloader-2
```
