### ISSUE TITLE
Font is broken even when ENABLE_CJK_FONT is set

### ISSUE THREAD

**Issue by qowmq** [jlesage/docker-jdownloader-2#106]
I set ENABLE_CJK_FONT=1 and jdownloader font name is "default" but the font is broken.
By default, Korean is used, and both Japanese and Chinese are broken.

Here is the docker-compose I used.
```
version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader2
    environment:
      - USER_ID=1030
      - GROUP_ID=100
      - TZ=Asia/Seoul
      - ENABLE_CJK_FONT=1
    volumes:
      - '/volume1/docker/jdownloader2/config:/config:rw'
      - '/volume2/video:/video:rw'
      - '/volumeUSB1/usbshare/incomplete:/incomplete:rw'
    network_mode: "container:gluetun"
    restart: on-failure:3
```

Does it have anything to do with the font related logs when starting the container?
```
[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: installing CJK font...
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz: UNTRUSTED signature
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: ERROR: unsatisfiable constraints:
[cont-init.d] 10-cjk-font.sh:   wqy-zenhei (missing):
[cont-init.d] 10-cjk-font.sh:     required by: world[wqy-zenhei]
[cont-init.d] 10-cjk-font.sh: exited 0.
```
