### ISSUE TITLE
Headless image with SAME volume configuration

### ISSUE THREAD

**Issue by AlexeiScherbakov** [jlesage/docker-jdownloader-2#112]
It would be perfect if also headless image with same volume configuration will be exists. For 95% of time GUI is not needed and it only consuming resources. But it is VERY usefull for troubleshooting

Main idea is to start GUI image
```
version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/jdownloader-2:/config:rw"
      - "$HOME/Downloads:/output:rw"
```
And when in is not needed stop it and turn to headless
```
version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2-headless
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/jdownloader-2:/config:rw"
      - "$HOME/Downloads:/output:rw"
```
If any problems - switch back to GUI image.
