### ISSUE TITLE
Can‘t install extra packages

### ISSUE THREAD

**Issue by mr-n0cturne** [jlesage/docker-jdownloader-2#118]
Hi again :)
I was too slow with answering the original topic so it has been closed. 

Ive tried to install curl via environment variable INSTALL_PACKAGES=curl / INSTALL_EXTRA_PKGS=curl. Unfortunatelly without success:

```
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: executing...
[cont-env    ] INSTALL_PACKAGES_INTERNAL: terminated successfully.
[cont-env    ] INSTALL_PACKAGES_INTERNAL: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-cjk-font.sh: executing...
[cont-init   ] 10-cjk-font.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-jwm.sh: executing...
[cont-init   ] 10-jwm.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: terminated successfully.
[cont-init   ] 10-vnc-password.sh: executing...
[cont-init   ] 10-vnc-password.sh: terminated successfully.
[cont-init   ] 10-web-data.sh: executing...
[cont-init   ] 10-web-data.sh: terminated successfully.
[cont-init   ] 10-x11-unix.sh: executing...
[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
[cont-init   ] 15-install-pkgs.sh: executing...
[cont-init   ] 15-install-pkgs.sh: installing requested package(s)...
[cont-init   ] 15-install-pkgs.sh: installing 'curl'...
[cont-init   ] 15-install-pkgs.sh: fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
[cont-init   ] 15-install-pkgs.sh: WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: temporary error (try again later)
[cont-init   ] 15-install-pkgs.sh: fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
[cont-init   ] 15-install-pkgs.sh: WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: temporary error (try again later)
[cont-init   ] 15-install-pkgs.sh: ERROR: unable to select packages:
[cont-init   ] 15-install-pkgs.sh:   curl (no such package):
[cont-init   ] 15-install-pkgs.sh:     required by: world[curl]
[cont-init   ] 15-install-pkgs.sh: terminated with error 1.

```

```
jdownloader2:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader2
    hostname: bf-srvddl
    restart: always
    mem_limit: 4096m
    cpus: 2.0
    volumes:
      - /share/CACHEDEV1_DATA/Container/jdownloader/config:/config
      - /share/Downloads/jdownloader:/output
    mac_address: 24:5E:BE:00:00:43
    environment:
      - TZ=Europe/Berlin
      - INSTALL_EXTRA_PKGS=curl
    dns:
      - 192.168.42.254
      - 1.1.1.1
      - 1.0.0.1
    networks:
      myBridgeNet:
        ipv4_address: 192.168.42.43

networks:
  myBridgeNet:
    driver: qnet
    driver_opts:
      iface: "eth2"
    ipam:
      driver: qnet
      options:
        iface: "eth2"
      config:
        - subnet: 192.168.42.0/24
          gateway: 192.168.42.254
```

_Originally posted by @bfrohn85 in https://github.com/jlesage/docker-jdownloader-2/issues/115#issuecomment-1324739651_
