### ISSUE TITLE
openbox.sh: terminated with error 1.

### ISSUE THREAD

**Issue by lackylucky** [jlesage/docker-jdownloader-2#134]
I receiv the following error since v23.01.1. The same error in v23.01.02. 
v22.12.2 is working fine.

Environment:
- Docker 20.10.22 with Portainer, running on an Ubuntu Server 22.04 VM.
- Config is stored on a CIF Volume.

> 2023-01-11T23:59:46.402037564Z [init        ] container is starting...
> 2023-01-11T23:59:46.402193381Z [cont-env    ] loading container environment variables...
> 2023-01-11T23:59:46.408997907Z [cont-env    ] APP_NAME: loading...
> 2023-01-11T23:59:46.422823126Z [cont-env    ] DISPLAY: executing...
> 2023-01-11T23:59:46.442897938Z [cont-env    ] DISPLAY: terminated successfully.
> 2023-01-11T23:59:46.443360060Z [cont-env    ] DISPLAY: loading...
> 2023-01-11T23:59:46.444514101Z [cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
> 2023-01-11T23:59:46.446476328Z [cont-env    ] DOCKER_IMAGE_VERSION: loading...
> 2023-01-11T23:59:46.452103166Z [cont-env    ] GTK_THEME: executing...
> 2023-01-11T23:59:46.459525576Z [cont-env    ] GTK_THEME: terminated successfully.
> 2023-01-11T23:59:46.459879958Z [cont-env    ] GTK_THEME: loading...
> 2023-01-11T23:59:46.460862369Z [cont-env    ] HOME: loading...
> 2023-01-11T23:59:46.464088452Z [cont-env    ] INSTALL_PACKAGES_INTERNAL: executing...
> 2023-01-11T23:59:46.466464320Z [cont-env    ] INSTALL_PACKAGES_INTERNAL: terminated successfully.
> 2023-01-11T23:59:46.466920331Z [cont-env    ] INSTALL_PACKAGES_INTERNAL: loading...
> 2023-01-11T23:59:46.467950251Z [cont-env    ] QT_STYLE_OVERRIDE: executing...
> 2023-01-11T23:59:46.471486467Z [cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
> 2023-01-11T23:59:46.471832426Z [cont-env    ] QT_STYLE_OVERRIDE: loading...
> 2023-01-11T23:59:46.472803498Z [cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
> 2023-01-11T23:59:46.480209063Z [cont-env    ] XDG_CACHE_HOME: loading...
> 2023-01-11T23:59:46.488212283Z [cont-env    ] XDG_CONFIG_HOME: loading...
> 2023-01-11T23:59:46.496238144Z [cont-env    ] XDG_DATA_HOME: loading...
> 2023-01-11T23:59:46.504224416Z [cont-env    ] XDG_RUNTIME_DIR: loading...
> 2023-01-11T23:59:46.506559786Z [cont-env    ] XDG_STATE_HOME: loading...
> 2023-01-11T23:59:46.511872042Z [cont-env    ] container environment variables initialized.
> 2023-01-11T23:59:46.511981706Z [cont-secrets] loading container secrets...
> 2023-01-11T23:59:46.512160090Z [cont-secrets] container secrets loaded.
> 2023-01-11T23:59:46.512259482Z [cont-init   ] executing container initialization scripts...
> 2023-01-11T23:59:46.514305825Z [cont-init   ] 10-certs.sh: executing...
> 2023-01-11T23:59:46.522906859Z [cont-init   ] 10-certs.sh: terminated successfully.
> 2023-01-11T23:59:46.523902264Z [cont-init   ] 10-check-app-niceness.sh: executing...
> 2023-01-11T23:59:46.531270771Z [cont-init   ] 10-check-app-niceness.sh: terminated successfully.
> 2023-01-11T23:59:46.535484240Z [cont-init   ] 10-cjk-font.sh: executing...
> 2023-01-11T23:59:46.538869421Z [cont-init   ] 10-cjk-font.sh: terminated successfully.
> 2023-01-11T23:59:46.539864577Z [cont-init   ] 10-clean-logmonitor-states.sh: executing...
> 2023-01-11T23:59:46.543326322Z [cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
> 2023-01-11T23:59:46.544309812Z [cont-init   ] 10-clean-tmp-dir.sh: executing...
> 2023-01-11T23:59:46.547260802Z [cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
> 2023-01-11T23:59:46.548191514Z [cont-init   ] 10-fontconfig-cache-dir.sh: executing...
> 2023-01-11T23:59:46.551740973Z [cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
> 2023-01-11T23:59:46.552673584Z [cont-init   ] 10-init-users.sh: executing...
> 2023-01-11T23:59:46.580790135Z [cont-init   ] 10-init-users.sh: terminated successfully.
> 2023-01-11T23:59:46.581629567Z [cont-init   ] 10-nginx.sh: executing...
> 2023-01-11T23:59:46.599147681Z [cont-init   ] 10-nginx.sh: terminated successfully.
> 2023-01-11T23:59:46.600012389Z [cont-init   ] 10-openbox.sh: executing...
> **2023-01-11T23:59:46.606852936Z [cont-init   ] 10-openbox.sh: ln: /config/xdg/data/themes/OpenboxTheme: Not supported**
> **2023-01-11T23:59:46.607891485Z [cont-init   ] 10-openbox.sh: terminated with error 1.**

**Comment by jlesage** [comment]
> Config is stored on a CIF Volume.

You mean CIFS ?  How did you created the mount ?  Are you sure that support for symbolic links is enabled ?

**Comment by lackylucky** [comment]
Hi @jlesage 

> You mean CIFS ? 

Sorry, yes I mean CIFS.`


>How did you created the mount ? 

I create the mount in the docker compose file like this:
```
version: '3.0'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2:v22.12.2
    #image: jlesage/jdownloader-2:latest
    ports:
      - "5800:5800/tcp"
    environment:
      - TZ=Europe/Zurich
      - KEEP_APP_RUNNING=1

    restart: unless-stopped
    volumes:
      - "config:/config:rw"
      - "downloads:/output:rw"

volumes:
  config:
    driver_opts:
      type: "cifs"
      device: "//172.16.2.230/docker/jdownloader2"
      o: username=userxy,password=123456789,vers=3.0,uid=1000,gid=1000      
  downloads:
    driver_opts:
      type: "cifs"
      device: "//172.16.2.230/downloads"
      o: username=userxy,password=123456789,vers=3.0,uid=1000,gid=1000
```


>Are you sure that support for symbolic links is enabled?

Are you mean the support for symlinks in ubuntu or in the docker container? In my other containers is this config working fine.
