### ISSUE TITLE
Unexpected error encountered: Script error in web GUI

### ISSUE THREAD

**Issue by redberry94** [jlesage/docker-jdownloader-2#140]
I get after fresh installation the following error message in the web GUI: `Unexpected error encountered: Script error.`. I used the following docker-compose configuration:

```  
jdownloader:
    # Port 8084
    container_name: jdownloader
    image: jlesage/jdownloader-2
    ports:
      - "8084:8084"
    volumes:
      - "./jdownloader/app/cfg:/config"
      - "/data/jdownloader:/output"
    restart: unless-stopped
    environment:
      - WEB_LISTENING_PORT=8084
```
