### ISSUE TITLE
[Bug] display freezes with version 4.6.x of base image

### ISSUE THREAD

**Issue by skycaptain** [jlesage/docker-jdownloader-2#211]
### Current Behavior

To solve Captchas, I install Chromium inside the container using INSTALL_PACKAGE="chromium". While versions 4.5.x of the base image worked perfectly fine, with versions 4.6.x the display freezes seconds after launching Chromium inside the container, not allowing to click anywhere or to solve Captchas.

### Expected Behavior

The VNC session not to freeze and similar behaviour to previous 4.5.x versions.

### Steps To Reproduce

Take the following compose file:
```yaml
version: '3'
services:
  jdownloader:
    image: jlesage/jdownloader-2
    environment:
       - USER_ID=1000
       - GROUP_ID=1000
       - DISPLAY_WIDTH=1920
       - DISPLAY_HEIGHT=1080
       - DARK_MODE=1
       - KEEP_APP_RUNNING=1
       - INSTALL_PACKAGES=chromium
    ports:
      - [redacted]
    restart: unless-stopped
    shm_size: 2gb
    volumes:
      - [redacted]
```

Then, setup JDownloader to use Chromium to solve captchas using `["/usr/bin/chromium-browser", "--no-sandbox", "%s"]` for `GeneralSettings: Browser Command Line` setting. Open a link that requires solving Captchas, install the browser plugin and watch the VNC session freeze.

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

See above

### Container log

```text
No related entry in logs.
```
