### ISSUE TITLE
[Bug] Continuous restarts afer update to v25.06.1

### ISSUE THREAD

**Issue by update-freak** [jlesage/docker-jdownloader-2#264]
### Current Behavior

After updating to the latest version v25.06.1 I recognised that in the logs the container continuously restarting.

### Expected Behavior

No continuous restarts

### Steps To Reproduce

Update to new version or create a new docker container with the docker-compose from above.

### Environment

- OS: Synology DSM
- OS version: 7.2.2
- CPU: Intel Celeron N3150 
- Docker version: 24.0.2-1535
- Device model: DS716+
- Browser/OS: Firebox 139

### Container creation

docker compose:

```
services:
  jdownloader2:
    image: jlesage/jdownloader-2
    container_name: JDownloader2
    ports:
      - 3129:3129
      - 5800:5800
      - 5801:5900
    volumes:
      - /volume1/docker/jdownloader2/config:/config:rw
      - /volume1/docker/jdownloader2/output:/output:rw
    environment:
      - USER_ID=1026
      - GROUP_ID=100
      - LANG=de_DE.UTF-8
      - TZ=Europe/Berlin
      - DARK_MODE=0 #Type in 0 instead of 1 if you want a light theme
      - WEB_AUTHENTICATION=1
      - SECURE_CONNECTION=1
      - MYJDOWNLOADER_EMAIL=EMAIL
      - MYJDOWNLOADER_PASSWORD=PASSWORT
      - MYJDOWNLOADER_DEVICE_NAME=NAS
      - JDOWNLOADER_HEADLESS=0
    restart: always
```

### Container log

```text
if necessary I will add
```

### Container inspect

```text

```
