### ISSUE TITLE
App display resolution

### ISSUE THREAD

**Issue by eckozen84** [jlesage/docker-jdownloader-2#42]
The "DISPLAY_WIDTH" and "DISPLAY_HEIGHT" environment variables don't have any effect on the resolution of JD2 (at least when access via VNC). It always remains at the default 1280x768 resolution.

I am using the latest docker-compose and docker-ce on Ubuntu 18.04.

**Comment by jlesage** [comment]
This is working for me... can you share the docker compose file you are using?

**Comment by eckozen84** [comment]
```
version: "3.7"
services:
  jd2:
    container_name: jd2
    network_mode: "docker_default"
    image: jlesage/jdownloader-2:latest
    restart: always
    ports:
      - "5801:5800"
      - "5902:5900"
      - "3129:3129"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DISPLAY_WIDTH = 1920
      - DISPLAY_HEIGHT = 1200
      - KEEP_APP_RUNNING = 1
    volumes:
      - "${DOCKDIR}/jd2_config:/config:rw"
      - "${USERDIR}/drivepool:/media/drivepool:rw"
```
