### ISSUE TITLE
How do I add some basic HTTP authentication?

### ISSUE THREAD

**Issue by janniksam** [jlesage/docker-jdownloader-2#44]
Is there a built in way, if you don't use a VPN connection?
Like there is with transmission daemon.

**Comment by janniksam** [comment]
This is my current state so far:

```
version: '3'

services:
  web:
    container_name: jd_container1
    restart: unless-stopped
    image: jlesage/jdownloader-2
    volumes:
      - "/docker/appdata/jdownloader-2:/config:rw"
      - "/home/Downloads:/output:rw"

  auth:
    container_name: basic-auth
    restart: unless-stopped
    image: beevelop/nginx-basic-auth
    ports:
      - "5800:80"
    environment:
      - HTPASSWD=foo:$$apr1$$odHl5EJN$$KbxMfo86Qdve2FH4owePn.
      - FORWARD_PORT=5800
    links:
      - web
```

But when I try to access JDownloader with name foo and password bar, the page is staying like this (white):

![bbb](https://user-images.githubusercontent.com/15337798/76150871-0228e800-60af-11ea-99f5-ef6425489385.png)

I haven't found anything useful in the logs so far, maybe you have any idea?
