### ISSUE TITLE
Download folder out from docker folder

### ISSUE THREAD

**Issue by matand77** [jlesage/docker-jdownloader-2#58]
When I set a volume on my synology, therefore external to the docker folder but still installed on volume  (which is where I have all the folders where I would use jdwonloader to download like music, film, etc.) .. Even setting it for folder download, it tells me "invalid download folder". 

Is it a permission problem? how could I solve?

**Comment by mr-bolle** [comment]
[Read the documentation User/Group IDs](https://github.com/jlesage/docker-jdownloader-2#usergroup-ids)

In this example you can set the User and Group ID from your Host Volume.
Please share your Host Volume permission `ls -la YourVolumePath` and the UserID `id $USER`

```
version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    environment:
      - UID=1000
      - GID=999

```
