### ISSUE TITLE
Change port from Environment Variables

### ISSUE THREAD

**Issue by eduarcor** [jlesage/docker-jdownloader-2#59]
Is there a way to change the port from the Environment Variables?
I am using Docker inside of Synology DSM.
As I am not really proficient with ports I am always creating the container with the option "Use the same network as Docker Host".
If not, can you support it? If you are not able to do it and you have more application which shares the same default port and you can change it, you never can run them at the same time.
Thanks

**Comment by mr-bolle** [comment]
Could you share your docker-compose enviroment settings.
You can change the Host Ports like you wish.
```
version: '3'
services:
  jdownloader-2:
....
    ports:
      - "5801:5800"
```
5801 = Host Port
5800 = Container Port
