### ISSUE TITLE
QNAP Container Station (Error)

### ISSUE THREAD

**Issue by pieromobile** [jlesage/docker-jdownloader-2#98]
After installation on my qnap container station, when starting jdownloader various update errors are displayed with consequent program shutdown.

**Error GUI**
![image](https://user-images.githubusercontent.com/6080222/158973153-0671e102-adda-40aa-8f50-948e428367a2.png)

![image](https://user-images.githubusercontent.com/6080222/158973226-14b4d382-6313-4958-a2f3-282bd9585338.png)

![image](https://user-images.githubusercontent.com/6080222/158973318-baf22692-8148-4931-aacb-b4a9db0d9319.png)

**Error Console**
![image](https://user-images.githubusercontent.com/6080222/158972786-bb07a9a2-4b06-4afb-bdd4-4e4c0efc36c6.png)

**Comment by pieromobile** [comment]
**After reinstal application**

![20220318-100954-SUPERPC-CASA](https://user-images.githubusercontent.com/6080222/158974191-e097a002-ae82-408e-b411-f15a6ca3d380.png)
![20220318-101000-SUPERPC-CASA](https://user-images.githubusercontent.com/6080222/158974196-dfa14dba-77d1-44be-9c5d-4319beb47fbd.png)

**Comment by jlesage** [comment]
How did you created the container ?  Can you share the `docker run ` command and/or the config ?

**Comment by mLgz0rn** [comment]
I got the same issue on unraid.
With both yours and ich777's image.
It happened after a recent update.

**Comment by jlesage** [comment]
After an update of what ?

**Comment by mLgz0rn** [comment]
> After an update of what ?

Of Jdownloader itself.

**Comment by pom2ter-git** [comment]
Hi !
Exactly the same problem for me. It may be a Container Station update that introduced this malfunction.
By digging a bit, I realize that what causes this crash for me is due to the fact that I modify the USER_ID, because I use a shared volume from the NAS to save my downloaded files... JDownloader is therefore no longer usable, because if I leave the default USER_ID=1000, this certainly allows me to correctly install my container and start JDownloader, but I no longer have access to my directory for writing (and I have then an error message from JDownloader)

**Comment by jlesage** [comment]
Is this still an issue with the latest image?

**Comment by liuk4friends** [comment]
Hi @jlesage,

Latest image (v22.11.1) doesn't work with my Qnap Container Station (version 2.6.2.574 2022/10/31).

Last working version for me is 1.72.1.

Below you can find my docker compose file that is working right now:

```
version: '3'
services:
  jdownloader2:
    image: jlesage/jdownloader-2:v1.7.2
    ports:
      - "5800:5800"
      - "3129:3129"
    volumes:
      - "/share/CACHEDEV1_DATA/Container/container-station-data/application/jdownloader2:/config:rw"
      - "/share/CACHEDEV2_DATA/Download/jd2:/output:rw"
```
